### login
POST http://localhost:3001/user/login
Content-Type: application/json

{
    "email": "20521153@gm.uit.edu.vn",
    "password": "123456789"
}

# test

### signup
POST http://localhost:3001/user/signup
Content-Type: application/json

{
    "name": "Đạiiiiiiiiiiiiiiiiiiii",
    "email": "02s153@gm.uit.edu.vn",
    "password": "123456789",
    "gender":"Nữ",
    "phoneNumber": "0123456789",
    "address": "Long An",
    "role": "user"
}


###Lấy thông tin user dựa vào id /user/:id
GET  http://localhost:3001/user/64742a1422be3a2b49ac76c6

### sửa thông tin user dựa vào id /user/:id
PATCH  http://localhost:3001/user/64742a1422be3a2b49ac76c6
Content-Type:  application/json

{
    "name": "Lê Minh Đạiiii",
    "gender": "nữuuuuu"
}

### thêm 1 hóa đơn /user/:userId/order
POST http://localhost:3001/user/123/order
Content-Type: application/json

{
  "sanphams": [
    {
      "productId": "P001",
      "name": "Product 1",
      "image": "image1.jpg",
      "price": 10.99,
      "category": "Category 1",
      "unit": "Unit 1",
      "quality": "Quality 1",
      "color": "Color 1",
      "mass": "Mass 1",
      "size": "Size 1"
    },
    {
      "productId": "P002",
      "name": "Product 2",
      "image": "image2.jpg",
      "price": 15.99,
      "category": "Category 2",
      "unit": "Unit 2",
      "quality": "Quality 2",
      "color": "Color 2",
      "mass": "Mass 2",
      "size": "Size 2"
    },
        {
      "productId": "P002",
      "name": "Product 2",
      "image": "image2.jpg",
      "price": 15.99,
      "category": "Category 2",
      "unit": "Unit 2",
      "quality": "Quality 2",
      "color": "Color 2",
      "mass": "Mass 2",
      "size": "Size 2"
    },
        {
      "productId": "P002",
      "name": "Product 2",
      "image": "image2.jpg",
      "price": 15.99,
      "category": "Category 2",
      "unit": "Unit 2",
      "quality": "Quality 2",
      "color": "Color 2",
      "mass": "Mass 2",
      "size": "Size 2"
    },
    {
      "productId": "P003",
      "name": "Product 3",
      "image": "image3.jpg",
      "price": 20.99,
      "category": "Category 3",
      "unit": "Unit 3",
      "quality": "Quality 3",
      "color": "Color 3",
      "mass": "Mass 3",
      "size": "Size 3"
    }
  ],
  "diachigiaohang": "Address 1",
  "phuongthucthanhtoan": "Payment method 1"
}

### xóa hóa đơn nếu tình trạng là: chưa xử lý
DELETE  http://localhost:3001/user/order/HD001

### lấy hóa đơn của 1 user /user/:id/order
GET  http://localhost:3001/user/123456/order


### lấy tất cả các sản phẩm
GET http://localhost:3001/product

### lấy 1 sản phẩm dựa vào id
GET http://localhost:3001/product/p02


######## các thao tác của ADMINN ########


###Lấy danh sách các user
GET http://localhost:3001/admin/user

### lấy tất cả các sản phẩm
GET http://localhost:3001/product/

### tìm sản phẩm theo tên
GET http://localhost:3001/product/search?name=nh

### lấy ra hóa đơn có tình trạng là "chưa xử lý"
GET http://localhost:3001/admin/order/unprocessed

